### ISSUE TITLE
Edited text lives in ram at 0

### ISSUE THREAD

**Issue by interfect** [orlof/dcdos-edit#2]
When I start typing in the editor, those characters are placed at address 0.

I only have to type a few tens of characters to end up overwriting some important code and crashing the editor.

Steps to reproduce:

* `EDIT test.txt`
* Hold down "A"
* See lots of 0x41 at the top of memory

**Comment by interfect** [comment]
Looks like maybe https://github.com/orlof/dcdos-edit/blob/master/src/edit.dasm16#L26-L33 need to depend on `buffer_ram_start`.

**Comment by orlof** [comment]
Woah, that was a total failure O.o

Thanks for the report :)

Fixed in 1.01 as you suggested and also did some code cleanup.
